"""Structural interfaces for data access.

Two implementations satisfy these Protocols: `supabase_repository` (production,
talks to Supabase via PostgREST/Storage) and `memory_repository` (in-process
fakes used by the test suite so CI never needs a live database).
"""

from typing import Any, Protocol


class UserRepository(Protocol):
    def create(self, fields: dict[str, Any]) -> dict[str, Any]: ...
    def get_by_id(self, user_id: str) -> dict[str, Any] | None: ...
    def get_many_by_ids(self, user_ids: list[str]) -> dict[str, dict[str, Any]]: ...
    def get_by_email(self, email: str) -> dict[str, Any] | None: ...
    def update(self, user_id: str, fields: dict[str, Any]) -> dict[str, Any] | None: ...
    def list_leaderboard(
        self, period: str, limit: int, offset: int
    ) -> tuple[list[dict[str, Any]], int]: ...
    def get_rank(self, user_id: str, period: str) -> dict[str, Any] | None: ...
    def list_all_ids(self) -> list[str]: ...
    def list_ids_with_birthday(self, month: int, day: int) -> list[str]: ...
    def list_ids_created_before(self, iso: str) -> list[str]: ...


class BookRepository(Protocol):
    def create(self, fields: dict[str, Any]) -> dict[str, Any]: ...
    def get_by_id(self, book_id: str) -> dict[str, Any] | None: ...
    def get_many_by_ids(self, book_ids: list[str]) -> dict[str, dict[str, Any]]: ...
    def list_by_user(
        self,
        user_id: str,
        status: str | None,
        q: str | None,
        genre: str | None,
        sort: str,
        page: int,
        size: int,
    ) -> tuple[list[dict[str, Any]], int]: ...
    def list_public_finished(
        self, user_id: str, sort: str, page: int, size: int
    ) -> tuple[list[dict[str, Any]], int]: ...
    def update(self, book_id: str, fields: dict[str, Any]) -> dict[str, Any] | None: ...
    def delete(self, book_id: str) -> bool: ...
    def finish(
        self,
        book_id: str,
        user_id: str,
        summary: str,
        rating: int | None,
        finished_at: str | None,
    ) -> dict[str, Any]: ...


class ReadingSessionRepository(Protocol):
    def log(
        self,
        book_id: str,
        user_id: str,
        pages_read: int,
        minutes: int | None,
        date: str | None,
    ) -> dict[str, Any]: ...
    def list_by_book(
        self, book_id: str, page: int, size: int
    ) -> tuple[list[dict[str, Any]], int]: ...
    def list_by_user_window(
        self, user_id: str, date_from: str, date_to: str
    ) -> list[dict[str, Any]]: ...
    def list_all_by_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def user_ids_active_since(self, iso: str) -> set[str]: ...


class BookmarkRepository(Protocol):
    def create(self, user_id: str, book_id: str) -> dict[str, Any]: ...
    def get_by_id(self, bookmark_id: str) -> dict[str, Any] | None: ...
    def exists(self, user_id: str, book_id: str) -> bool: ...
    def list_by_user(
        self, user_id: str, page: int, size: int
    ) -> tuple[list[dict[str, Any]], int]: ...
    def bookmarked_book_ids(self, user_id: str, book_ids: list[str]) -> set[str]: ...
    def delete(self, bookmark_id: str) -> bool: ...
    def delete_by_book(self, user_id: str, book_id: str) -> bool: ...


class DeviceTokenRepository(Protocol):
    def upsert(self, user_id: str, token: str, platform: str | None) -> dict[str, Any]: ...
    def delete(self, token: str) -> None: ...
    def list_tokens_for_user(self, user_id: str) -> list[str]: ...
    def list_tokens_for_users(self, user_ids: list[str]) -> list[str]: ...


class NotificationRepository(Protocol):
    def create(
        self, user_id: str, title: str, body: str, image_url: str | None, data: dict
    ) -> dict[str, Any]: ...
    def create_bulk(
        self, user_ids: list[str], title: str, body: str, image_url: str | None, data: dict
    ) -> int: ...
    def get_by_id(self, notification_id: str) -> dict[str, Any] | None: ...
    def list_by_user(
        self, user_id: str, unread_only: bool, page: int, size: int
    ) -> tuple[list[dict[str, Any]], int, int]: ...
    def mark_read(self, notification_id: str) -> dict[str, Any]: ...
    def mark_all_read(self, user_id: str) -> int: ...
    def delete(self, notification_id: str) -> bool: ...
    def unread_count(self, user_id: str) -> int: ...


class RefreshTokenRepository(Protocol):
    def create(self, jti: str, user_id: str, family_id: str, expires_at: str) -> None: ...
    def get(self, jti: str) -> dict[str, Any] | None: ...
    def revoke(self, jti: str) -> None: ...
    def revoke_family(self, family_id: str) -> None: ...
    def revoke_all_for_user(self, user_id: str) -> None: ...


class PasswordResetRepository(Protocol):
    def create(self, user_id: str, token_hash: str, expires_at: str) -> dict[str, Any]: ...
    def get_by_hash(self, token_hash: str) -> dict[str, Any] | None: ...
    def mark_used(self, reset_id: str) -> None: ...


class WebhookEventRepository(Protocol):
    def was_processed(self, event_id: str) -> bool: ...
    def mark_processed(self, event_id: str) -> None: ...


class ContentRepository(Protocol):
    def list_quotes(self, category: str | None, limit: int) -> list[dict[str, Any]]: ...
    def list_summaries(self, page: int, size: int) -> tuple[list[dict[str, Any]], int]: ...
    def create_summary(self, fields: dict[str, Any]) -> dict[str, Any]: ...
